#!/bin/bash
FROM arm32v7/python:3.10-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN apt-get update && apt-get install -y gcc make
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]